"""5_add report_status field to order table

Revision ID: 205a8d7a33d0
Revises: 9bc44c34aa57
Create Date: 2024-10-05 12:24:41.874987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a8d7a33d0'
down_revision: Union[str, None] = '9bc44c34aa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('report_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'report_status')
    # ### end Alembic commands ###
