"""6_add orders field to daily and table report tables

Revision ID: 2a4ba448f122
Revises: 205a8d7a33d0
Create Date: 2024-10-05 16:29:43.114527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4ba448f122'
down_revision: Union[str, None] = '205a8d7a33d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('orders', sa.JSON(), nullable=True))
    op.add_column('table_report', sa.Column('orders', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_report', 'orders')
    op.drop_column('daily_report', 'orders')
    # ### end Alembic commands ###
