"""add table and products income fields to table report model

Revision ID: 6bb29e2b7c49
Revises: a364787f3a1b
Create Date: 2024-10-09 07:22:47.476124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb29e2b7c49'
down_revision: Union[str, None] = 'a364787f3a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_report', sa.Column('table_income', sa.Integer(), nullable=True))
    op.add_column('table_report', sa.Column('products_income', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_report', 'products_income')
    op.drop_column('table_report', 'table_income')
    # ### end Alembic commands ###
