"""3_set nullable true to table_id field on order

Revision ID: 90a023091d5d
Revises: e0568f199b4e
Create Date: 2024-09-27 16:27:09.750391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a023091d5d'
down_revision: Union[str, None] = 'e0568f199b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('order_table_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'table', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_table_id_fkey', 'order', 'table', ['table_id'], ['id'])
    op.alter_column('order', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
