"""add table and products income fields to order model

Revision ID: a364787f3a1b
Revises: c6e30d27fccb
Create Date: 2024-10-09 06:29:20.469924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a364787f3a1b'
down_revision: Union[str, None] = 'c6e30d27fccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('table_income', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('products_income', sa.Float(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'products_income')
    op.drop_column('order', 'table_income')
    # ### end Alembic commands ###
