"""add daily_report and table_report, add products field to order

Revision ID: e0568f199b4e
Revises: e60a7520dfc1
Create Date: 2024-09-26 12:11:01.920287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0568f199b4e'
down_revision: Union[str, None] = 'e60a7520dfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_income', sa.Integer(), nullable=False),
    sa.Column('table_income', sa.Integer(), nullable=False),
    sa.Column('product_income', sa.Integer(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('total_play_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_id'), 'daily_report', ['id'], unique=True)
    op.create_table('table_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('total_income', sa.Integer(), nullable=False),
    sa.Column('total_play_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_report_id'), 'table_report', ['id'], unique=True)
    op.add_column('order', sa.Column('table_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'table_price')
    op.drop_index(op.f('ix_table_report_id'), table_name='table_report')
    op.drop_table('table_report')
    op.drop_index(op.f('ix_daily_report_id'), table_name='daily_report')
    op.drop_table('daily_report')
    # ### end Alembic commands ###
